#!/bin/sh

docker stop wordpress mysql
docker rm wordpress mysql

# docker build --no-cache -t wordpress -f dockerfiles/wordpress .
docker build -t wordpress -f dockerfiles/wordpress .

docker run -d --name mysql -p 3306:3306 --env-file ./.env mysql:5.7
docker run --link mysql:mysql -p 80:80 -d --name wordpress --env-file ./.env wordpress
